spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 12345
  jpa:
    open-in-view: false
    properties:
      show_sql: true
      format_sql: true
  mail:
    host: smtp.gmail.com
    username: add.mapcejib@mail.ru
    password: Tarantul2001_1601
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
